package study.ch.Dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import study.ch.Bean.Teacher;

public interface TeacherMapper {
    /**
     * 批量插入
     */
    void insertBatch(@Param("teachers") List<Teacher> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Mar 01 20:34:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Mar 01 20:34:11 CST 2021
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Mar 01 20:34:11 CST 2021
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Mar 01 20:34:11 CST 2021
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbg.generated Mon Mar 01 20:34:11 CST 2021
     */
    int updateByPrimaryKey(Teacher record);
}